language: java
jdk:
  - openjdk13
os:
  - linux
dist: bionic

services:
    - postgresql

addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-client-11
  sonarcloud:
    organization: the-pragmatic-dev
    token: $SONAR_TOKEN

install: ./mvnw dependency:resolve
before_script:
  - psql --version
  - psql -c 'create database travis_ci_test;' -U postgres
  - ./scripts/init.sh /var/lib/meco/ travis

stages:
  - test

jobs:
  include:
    - stage: test
    # checks compilation and checkstyle errors then run unit and integration tests before pushing results to sonarcloud.
    # jpa logs are disabled to avoid travis log length error
    - script: ./mvnw clean verify -Dspring.jpa.show-sql=false -P all sonar:sonar