language: java
jdk:
  - openjdk13
os:
  - linux
dist: xenial
addons:
sonarcloud:
  organization: the-pragmatic-dev
  token:
    secure: $SONAR_TOKEN
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar