language: java
jdk:
  - openjdk13
os:
  - linux
dist: xenial

addons:
sonarcloud:
  organization: the-pragmatic-dev
  token:
    secure: $SONAR_TOKEN

stages:
  - compile
  - unit tests
  - integration tests
  - deploy

jobs:
  include:
    - stage: compile
      script: ./mvnw clean compile # compilation and checkstyle errors
    - stage: unit tests
      script: ./mvnw clean verify sonar:sonar # run unit tests and push results to sonarcloud
    - stage: integration tests
      script: ./mvnw clean verify -P integration # run integration tests
    - stage: deploy
      script: echo TODO # TODO