language: java
jdk:
  - openjdk13
os:
  - linux
dist: bionic

services:
    - postgresql

addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
  sonarcloud:
    organization: the-pragmatic-dev
    token: $SONAR_TOKEN

install: ./mvnw dependency:resolve
before_script:
  - psql --version
  - psql -c 'create database travis_ci_test;' -U postgres
  - whoami
  - sudo ./scripts/init.sh /var/lib/meco/ root

stages:
  - test
  - provision
  - deploy

jobs:
  include:
    - stage: test
    - script: ./mvnw clean compile # compilation and checkstyle errors
    - script: ./mvnw clean verify sonar:sonar # run unit tests and push results to sonarcloud
    - script: ./mvnw clean verify -P integration # run integration tests
    - stage: provision
    - script: echo TODO # TODO: run terraform
    - stage: deploy
      script: echo TODO # TODO: deploy to digitalocean