server:
    port: ${PORT:8080}

spring:
    profiles:
        active: dev
    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
    thymeleaf:
        cache: false
    output:
        ansi:
            enabled: always
    data:
        web:
            pageable:
                default-page-size: 8
                max-page-size: 8
    datasource:
        url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/travis_ci_test}
        username: ${DATASOURCE_USERNAME:postgres}
        password: ${DATASOURCE_PASSWORD:}
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    time_zone: ${TIMEZONE:UTC}
                    lob:
                        non_contextual_creation: true
    flyway:
        locations: classpath:/db/migration,classpath:/db/data/dev
        clean-on-validation-error: true

async:
    core-pool-size: ${ASYNC_CORE_POOL_SIZE:5}
    max-pool-size: ${ASYNC_MAX_POOL_SIZE:10}
    queue-capacity: ${ASYNC_QUEUE_CAPACITY:10}

security:
    token:
        secret-key: ${TOKEN_SECRET_KEY:secret-key}
        access-token-expiration-minutes: 5
        refresh-token-expiration-days: 7

management:
    endpoints:
        web:
            cors:
                allowed-origins: '*'
                allowed-methods: GET
            exposure:
                include: info, health, flyway, metrics

info:
    app:
        version: 
            name: ${VERSION_NAME:alpha}
            major: ${VERSION_MAJOR:0}
            minor: ${VERSION_MINOR:0}
            patch: ${VERSION_PATCH:0}

stripe:
    secret-key: ${STRIPE_SECRET_KEY:secret_key}

mailgun:
    url: https://api.mailgun.net/v3/%s.mailgun.org
    domain: ${MAILGUN_DOMAIN:domain}
    secret-key: ${MAILGUN_SECRET_KEY:secret_key}
    from:
        name: ${MAILGUN_FROM_NAME:name}
        email: ${MAILGUN_FROM_EMAIL:email}
    templates:
      - name: 'account-created'
        subject: 'Welcome to MECO!'
      - name: 'account-forgotten-password'
        subject: 'Reset your MECO password'
      - name: 'account-reset-password'
        subject: 'Your MECO password has been changed'
      - name: 'account-unrecognized-device'
        subject: 'Unrecognized device signed in to your MECO account'
      - name: 'key-created'
        subject: 'A new key was added to your account'
      - name: 'key-deleted'
        subject: 'A key was deleted from your account'

perspective:
    url: https://commentanalyzer.googleapis.com/v1alpha1
    secret-key: ${PERSPECTIVE_SECRET_KEY:secret_key}
            
kms:
    api-key-limit: ${API_KEY_LIMIT:10}

geolite2:
    name: GeoLite2-City.mmdb
    permalink: ${GEOLITE_URL:https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=YOUR_LICENSE_KEY&suffix=tar.gz}
    directory: ${GEOLITE_DIRECTORY:/var/lib/meco/}

logging:
  config: classpath:log4j2.dev.properties

bucket:
    capacity: 10000
    tokens: 10000
    minutes: 1

---

spring:
    profiles: prod
    jpa:
        show-sql: false
    flyway:
        locations: classpath:/db/migration
        clean-on-validation-error: false
    security:
        token:
            access-token-expiration-minutes: 5
            refresh-token-expiration-days: 7

logging:
    config: classpath:log4j2.prod.properties

bucket:
    capacity: 20
    tokens: 20
    minutes: 1
